#!/bin/sh

DOMAIN="$1"

if [ -z "$DOMAIN" ]; then
  echo "Domain name must be defined" 1>&2
  exit 1
fi

cd /zones || exit 1

echo "Generating ZSK & KSK keys for '${DOMAIN}'"
ZSK=$(ldns-keygen -a ECDSAP384SHA384 -b 384 "$DOMAIN")
KSK=$(ldns-keygen -k -a ECDSAP384SHA384 -b 384 "$DOMAIN")

rm -f "$ZSK".ds "$KSK".ds

mv "$ZSK".key     "K${DOMAIN}.zsk.key"
mv "$ZSK".private "K${DOMAIN}.zsk.private"

mv "$KSK".key     "K${DOMAIN}.ksk.key"
mv "$KSK".private "K${DOMAIN}.ksk.private"

chmod 600 -- *.private
exit 0